package network;

public enum Requests {

	UPDATE_SERVER_DATA, TICKET_REQUEST, FULL_DATA_REQUEST, CLIENTS_CONCERTS_REQUEST, FULL_DATA_WRITEN,
	ASK_FOR_FULL_DATA, FULL_DATA_TO_ADMIN, SERVER_TO_CLIENT_CONCERTS, ASK_FOR_CLIENT_CONCERTS,CLIENT_ASK_FOR_TICKETS,
	SERVER_TICKETS_TO_CLIENT, TICKETS_PURCHASE_RESPONSE, ASK_FOR_TICKETS_PURCHASE, PURCHASE_COMPLETED, 
	PURCHASE_ERROR, UPDATE_30, CLIENT_ASK_FOR_TICKETS_2;
}
